global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Spring Boot Risk Service
  - job_name: 'risk-service'
    static_configs:
      - targets: ['risk-service:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s

  # Python Analytics Service
  - job_name: 'analytics-service'
    static_configs:
      - targets: ['analytics-service:9091']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # Redis metrics (if available)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379'] 